// The one place the site gets the maze demo from: a copy of the maze-bot build in src/vendor/maze-bot/
// (generated by `npm run sync:site` in the maze-bot repo; see SOURCE.txt there, don't edit by hand).
export { mountMazeDemo, type MazeDemoHandle, type MazeDemoOptions } from '../vendor/maze-bot/maze-bot.js';
